### ISSUE TITLE
Add indicator target specification

### ISSUE THREAD

**Issue by allan-on** [OpenSRP/opensrp-client-goldsmith#66]
- [x] Introduce the concept of the target against which performance progress is computed. 
This will be tied to the 
a) Key health indicators  
b) Tasks on the My Performance section
~- [ ] This should ideally be set on the server (via an API call or OpenSRP web UI) then synced to the client devices~
- [x] The targets should be retrieved prior to doing any computations

**Comment by githengi** [comment]
Targets are currently hard coded.

@allan-allay to review use of server settings for targets and provide an LOE
