### ISSUE TITLE
Update core with latest master changes

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-goldsmith#69]
The client core update will also update the plan evaluator library used. The task property `executionPeriod` changes from a single primitive value to an object. This means that the new client core has to be used with the specific plan evaluator supporting the task property `executionPeriod` as an object.

Some rules in the current evaluation library change and less ambigous while custom functionality for closing tasks will be discarded. This requires an update of the PNC & ANC plan to use the updated functionality on plan evaluator v1.2.2 (action authoring to close completed tasks is a bit different from v01.6. It also requires testing)

- [x] Make sure the create task action work wells
- [x] Change the close task action for PNC  & ANC tasks to work with the new evaluator library and core library

**Comment by githengi** [comment]
@ekigamba to provide the LOE

**Comment by ekigamba** [comment]
**LOE = 6 hours**
